# Run when commits are pushed to main
on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
      - main

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read
  actions: write 


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
         token: ${{ secrets.SUBMODULE_PAT }}  
         submodules: recursive
      - name: Install azd
        uses: Azure/setup-azd@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.x.x
            9.x.x

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Restore NuGet Packages
        run: dotnet restore FamilyApplication.AspireApp.sln
        working-directory: src

      - name: Build Solution
        run: dotnet build FamilyApplication.AspireApp.sln --no-restore
        working-directory: src

      - name: Run Tests
        run: dotnet test FamilyApplication.AspireApp.sln --no-build --verbosity normal
        working-directory: src
        env:
         Azure__SubscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
         Azure__Location: ${{ vars.AZURE_LOCATION }}
         Azure__ResourceGroup: ${{ vars.AZURE_ENV_NAME }}  # Adjust if your resource group name differs
         Azure__AllowResourceGroupCreation: true  # Optional, but enables auto-creation if needed

      - name: Increment Build Number
        run: |
          CURRENT_BUILD=$(curl -s -H "Authorization: token ${{ github.token }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/variables/BUILD_NUMBER | jq -r .value)
          NEW_BUILD=$((CURRENT_BUILD + 1))
          echo "BUILD_NUMBER=$NEW_BUILD" >> $GITHUB_ENV

      - name: Enable Experimental Features
        run: |
          azd config set alpha.aca.persistDomains on
          azd config set alpha.aca.persistIngressSessionAffinity on
        working-directory: src/FamilyApplication.AspireApp.AppHost

      - name: Provision Infrastructure
        run: azd up --no-prompt
        working-directory: src/FamilyApplication.AspireApp.AppHost
        env:
         AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
         AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
         AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
         
      - name: Update Build Number in Repo
        if: success()  # Ensures it only updates on success
        run: |
          curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/variables/BUILD_NUMBER -d "{\"name\":\"BUILD_NUMBER\",\"value\":\"${{ env.BUILD_NUMBER }}\"}"
